language: python
python:
  - "3.6"
install: pip install tox-travis
script: tox
deploy:
  provider: pypi
  user: $PYPI_USER_NAME
  password: $PYPI_PASSWORD
  server: $PYPI_URL
  distributions: "bdist_wheel"
  on:
    branch: master
  verbose: true